#!/bin/bash

echo 'Starting Build'
mvn -f ~/grabber/pom.xml clean install
echo 'Starting Application'
nohup java -Dlogging.configurationFile=~/grabber/src/main/resources/log4j2.xml -Djava.awt.headless=true -server -jar ~/grabber/build/dependency/grabber-1.0-SNAPSHOT.jar $1 > ./run.out 2>&1 &
echo ' '
echo 'to see logs run: tail -F ~/grabber/logs/app.log'
echo ' '
echo 'to monitor health of grabber app run: curl http://localhost:8080/health'
echo ' '
